accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.Register.as_view(), name='register')
]

engineering/urls.py
from django.urls import path

from engineering import views

app_name = 'engineering'

urlpatterns = [
    path('create/ac_model/', views.CreateACModel.as_view(), name='ac_model_add'),
    path('create/effectivity/', views.CreateEffectivity.as_view(), name='effectivity_add'),
    path('create/ac/', views.CreateAC.as_view(), name='ac_add'),
    path('create/control/', views.CreateControl.as_view(), name='control_add'),
    path('create/rotable_pn/', views.CreateRotablePN.as_view(), name='rotable_pn_add'),
    path('create/repairable_pn/', views.CreateRepairablePN.as_view(), name='repairable_pn_add'),
    path('create/expendable_pn/', views.CreateExpendablePN.as_view(), name='expendable_pn_add')
]

opencamo/urls.py
from django.contrib import admin
from django.urls import path, include

import opencamo.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', opencamo.views.IndexPage.as_view(), name='index'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('system_settings/', include('system_settings.urls', namespace='system_settings')),
    path('engineering/', include('engineering.urls', namespace='engineering'))
]

system_settings/urls.py
from django.urls import path

from system_settings import views

app_name = 'system_settings'

urlpatterns = [
    path('location/add/', views.CreateLocation.as_view(), name='location_add'),
    path('unit/add/', views.CreateUnit.as_view(), name='unit_add'),
    path('airport/add/', views.CreateAirport.as_view(), name='airport_add'),
    path('location/list/', views.ListLocation.as_view(), name='location_list')
]

templates/base.html
<!DOCTYPE html>
{% load django_bootstrap5 %}
{% load static %}
<html lang="en" class="h-100">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  {% bootstrap_css %}
  {% bootstrap_javascript %}
  {% bootstrap_messages %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
  {% block head %}{% endblock %}
</head>
<body class="d-flex flex-column h-100 bg-dark">

<header>
  <nav class="navbar navbar-dark navbar-expand-lg bg-navigation">
    <div class="container-fluid justify-content-around">
      <a class="navbar-brand" href="{% url 'index' %}"><i class="bi bi-airplane me-2"></i>openCAMO</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% if user.is_authenticated %}
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Engineering</a>
            <ul class="dropdown-menu dropdown-menu-dark">
              <li><a class="dropdown-item" href="{% url 'engineering:ac_model_add' %}">Add AC Model</a></li>
              <li><a class="dropdown-item" href="{% url 'engineering:ac_add' %}">Add AC</a></li>
              <li><a class="dropdown-item" href="{% url 'engineering:effectivity_add' %}">Add Effectivity</a></li>
              <li><a class="dropdown-item" href="{% url 'engineering:control_add' %}">Add Control</a></li>
              <li><a class="dropdown-item" href="{% url 'engineering:rotable_pn_add' %}">Add Rotable PN</a></li>
              <li><a class="dropdown-item" href="{% url 'engineering:repairable_pn_add' %}">Add Repairable PN</a></li>
              <li><a class="dropdown-item" href="{% url 'engineering:expendable_pn_add' %}">Add Expendable PN</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Planning</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Flight Ops</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Inventory</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Orders</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Settings</a>
            <ul class="dropdown-menu dropdown-menu-dark">
              <li><a class="dropdown-item" href="{% url 'system_settings:unit_add' %}">Add Unit</a></li>
              <li><a class="dropdown-item" href="{% url 'system_settings:location_add' %}">Add Location</a></li>
              <li><a class="dropdown-item" href="{% url 'system_settings:airport_add' %}">Add Airport</a></li>
              <li><a class="dropdown-item" href="{% url 'system_settings:location_list' %}">List Locations</a></li>
            </ul>
          </li>
        </ul>
        <ul class="navbar-nav ms-md-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
          </li>
        </ul>
        {% else %}
        <ul class="navbar-nav ms-md-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
          </li>
        </ul>
        {% endif %}
      </div>
    </div>
  </nav>
</header>


<main class="flex-shrink-0">
    <div class="container mt-2">
      {% block content %}{% endblock %}
    </div>
</main>

<footer class="footer mt-auto py-3 text-center bg-navigation">
  <div class="container">
    <span>Footer content</span>
  </div>
</footer>

</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
openCAMO
{% endblock %}

{% block content %}
<h1 class="text-center">Hello world!</h1>
{% endblock %}